'use client';
import {useState} from 'react';
const colors=['#4A87FF','#996BFF','#FF61A8','#FF4D4D','#FF8F3D','#FFD638','#33D678','#33CCC2','#4A87FF','#996BFF','#FF61A8','#FF4D4D'];
export default function Home(){const [active,setActive]=useState(1);return <main>
<nav><div className="brand">Midi CoPilot</div><div className="navlinks"><a href="#how">How it works</a><a href="#features">Features</a><a className="pill" href="#download">Get the app</a></div></nav>
<section className="hero"><div className="eyebrow"><span/>CONNECTED · SHOW READY</div><h1>Your whole show.<br/><em>One tap away.</em></h1><p>Wireless MIDI cue control built for the stage. Fire tracks, cues and transport commands from iPhone or iPad—instantly.</p><div className="actions"><a className="primary" href="#download">Get Midi CoPilot</a><a className="secondary" href="#how">See how it works ↓</a></div><div className="phone"><img src="/app-main.png" alt="Midi CoPilot cue interface"/></div></section>
<section id="how" className="story"><div className="kicker">FROM TAP TO SHOW</div><h2>Your laptop can stay<br/>where it belongs.</h2><p className="lede">Midi CoPilot turns the device already in your hand into a stage-ready wireless cue controller.</p><div className="flow"><div><b>01</b><h3>Tap</h3><p>Hit a large, color-coded cue from anywhere on stage.</p></div><i>→</i><div><b>02</b><h3>Send</h3><p>Your command travels wirelessly to Midi CoPilot Link on your Mac.</p></div><i>→</i><div><b>03</b><h3>Fire</h3><p>Link passes MIDI straight to your show software.</p></div></div></section>
<section className="demo"><div className="demoCopy"><div className="kicker">TRY IT</div><h2>Built for the moment<br/>you can't miss.</h2><p>Tap a cue. This is the same visual language your crew sees during a show.</p><div className="status"><span/> Cue {active} fired · YOU</div></div><div className="grid">{colors.map((c,i)=><button key={i} onClick={()=>setActive(i+1)} style={{'--c':c}} className={active===i+1?'active':''}><span>{i+1}</span>Cue {i+1}</button>)}</div></section>
<section id="features" className="features"><div className="kicker">STAGE READY</div><h2>Simple at rehearsal.<br/>Serious at showtime.</h2><div className="featuregrid"><article><strong>64</strong><h3>Cues on iPad</h3><p>Up to 24 on iPhone and an 8 × 8 grid on iPad, portrait or landscape.</p></article><article><strong>↻</strong><h3>Always connected</h3><p>Rock-solid Wi‑Fi with auto-reconnect and Bluetooth backup.</p></article><article><strong>●</strong><h3>Everyone stays in sync</h3><p>Every connected device highlights the current cue and shows who fired it.</p></article><article><strong>⌁</strong><h3>Showtime lock</h3><p>Approve devices on the Mac, then lock the system down when the show starts.</p></article></div></section>
<section className="screens"><div><div className="kicker">MAKE IT YOURS</div><h2>Your cues.<br/>Your colors.<br/>Your show.</h2><p>Name every cue, assign MIDI CC values, choose press and release behavior, and map dedicated Play and Stop controls.</p></div><div className="stack"><img src="/app-cues.png" alt="Cue setup"/><img src="/app-settings.png" alt="MIDI settings"/></div></section>
<section id="download" className="cta"><div className="orb"/><div className="brand big">Midi CoPilot</div><h2>Leave the laptop.<br/>Run the show.</h2><p>Wireless MIDI cue control for iPhone and iPad.</p><div className="actions center"><a className="primary" href="#">App Store — Coming Soon</a><a className="secondary" href="#">Midi CoPilot Link for Mac</a></div></section>
<footer><div className="brand">Midi CoPilot</div><p>Your whole show, one tap away.</p><small>© 2026 Midi CoPilot</small></footer>
</main>}
